# Generated by Django 3.2.10 on 2022-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('PersonID', models.IntegerField(primary_key=True, serialize=False)),
                ('LastName', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=10)),
            ],
        ),
    ]
