# Generated by Django 4.1.1 on 2022-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_amenity_item_menu_nagstudent_drink_store_item_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Initial', models.CharField(max_length=25)),
                ('CompanyName', models.CharField(max_length=35)),
                ('Area', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='store',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
