# Generated by Django 4.1.1 on 2022-09-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_employee_remove_drink_item_remove_item_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='store',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
